
default: &default
  adapter: postgresql
  encoding: unicode
  
  pool: 5

development:
  <<: *default
  database: freshlogs_development

test:
  <<: *default
  database: freshlogs_test

production:
  <<: *default
  database: freshlogs_production
  username: freshlogs
  password: <%= ENV['FRESHLOGS_DATABASE_PASSWORD'] %>
